### ISSUE TITLE
希望能再完善JE的TPA界面

### ISSUE THREAD

**Issue by MC-Nirvana** [RenYuan-MC/Tpa#1]
BE的TPA界面经过测试，很不错。但我发现插件还附带了一套用于JE的TPA界面。我测试了下后发现不是太好用（只能进行tpa，不能进行tpahere）希望能够改进一下（例如左键点击是tpa，右键点击是tpahere）另外也可以按照BE的TPA界面那样，给JE的TPA界面加一个点击即可接受、拒绝传送请求的UI，希望以上建议能够采纳。

**Comment by MC-Nirvana** [comment]
搞错插件了，后来删了那个插件后发现JE的UI是另外一个插件的UI，不过这个插件要是也能有就更好了

**Comment by lRENyaaa** [comment]
我可以尝试去实现下JE的UI,不过应该不会很快完成

**Comment by MC-Nirvana** [comment]
没事的，不急。另外BE的ui下那个开关后面的文字可以随着开关状态变动吗？如果可以的话就更好了（例如开关打开的时候后面文字显示将玩家传送到身边，关闭的情况下显示传送到玩家身边）

**Comment by lRENyaaa** [comment]
> 没事的，不急。另外BE的ui下那个开关后面的文字可以随着开关状态变动吗？如果可以的话就更好了（例如开关打开的时候后面文字显示将玩家传送到身边，关闭的情况下显示传送到玩家身边）

这个从理论上来说不太可能,基岩版的Form不是动态的,不过也许可以用Step Slider替代Toggle来实现

**Comment by MC-Nirvana** [comment]
好吧，如果太麻烦或者不可能就算了。
